<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-FJDSB4Q" failures="2" tests="2" name="Default test(failed)" time="0.066" errors="0" timestamp="2021-11-26T12:40:29 IST">
  <testcase classname="testNGFramework.ExecutionFailedTestInTestNG" name="test4" time="0.018">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGFramework.ExecutionFailedTestInTestNG.test4(ExecutionFailedTestInTestNG.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="testNGFramework.ExecutionFailedTestInTestNG" name="test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGFramework.ExecutionFailedTestInTestNG.test2(ExecutionFailedTestInTestNG.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testNGFramework.ExecutionFailedTestInTestNG" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="testNGFramework.ExecutionFailedTestInTestNG" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
